### ISSUE TITLE
16.04 64bit安装wechat_2.6.8.52后无法正常启动

### ISSUE THREAD

**Issue by 1215998192** [wszqkzqk/deepin-wine-ubuntu#170]
启动日志:
myname@myname:~/下载$ /opt/deepinwine/apps/Deepin-WeChat/run.sh
Run Deepin-WeChat 2.6.8.52deepin0 c:/Program Files/Tencent/WeChat/WeChat.exe
run Deepin-WeChat progress pid 
Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.
总用量 0
lrwxrwxrwx 1 myname myname 10 8月  28 10:59 c: -> ../drive_c
lrwxrwxrwx 1 myname myname 10 8月  28 10:48 com1 -> /dev/ttyS0
lrwxrwxrwx 1 myname myname 10 8月  28 10:48 com10 -> /dev/ttyS9
lrwxrwxrwx 1 myname myname 11 8月  28 10:48 com11 -> /dev/ttyS10
lrwxrwxrwx 1 myname myname 11 8月  28 10:48 com12 -> /dev/ttyS11
lrwxrwxrwx 1 myname myname 11 8月  28 10:48 com13 -> /dev/ttyS12
lrwxrwxrwx 1 myname myname 11 8月  28 10:48 com14 -> /dev/ttyS13
lrwxrwxrwx 1 myname myname 11 8月  28 10:48 com15 -> /dev/ttyS14
lrwxrwxrwx 1 myname myname 11 8月  28 10:48 com16 -> /dev/ttyS15
lrwxrwxrwx 1 myname myname 11 8月  28 10:48 com17 -> /dev/ttyS16
lrwxrwxrwx 1 myname myname 11 8月  28 10:48 com18 -> /dev/ttyS17
lrwxrwxrwx 1 myname myname 11 8月  28 10:48 com19 -> /dev/ttyS18
lrwxrwxrwx 1 myname myname 10 8月  28 10:48 com2 -> /dev/ttyS1
lrwxrwxrwx 1 myname myname 11 8月  28 10:48 com20 -> /dev/ttyS19
lrwxrwxrwx 1 myname myname 11 8月  28 10:48 com21 -> /dev/ttyS20
lrwxrwxrwx 1 myname myname 11 8月  28 10:48 com22 -> /dev/ttyS21
lrwxrwxrwx 1 myname myname 11 8月  28 10:48 com23 -> /dev/ttyS22
lrwxrwxrwx 1 myname myname 11 8月  28 10:48 com24 -> /dev/ttyS23
lrwxrwxrwx 1 myname myname 11 8月  28 10:48 com25 -> /dev/ttyS24
lrwxrwxrwx 1 myname myname 11 8月  28 10:48 com26 -> /dev/ttyS25
lrwxrwxrwx 1 myname myname 11 8月  28 10:48 com27 -> /dev/ttyS26
lrwxrwxrwx 1 myname myname 11 8月  28 10:48 com28 -> /dev/ttyS27
lrwxrwxrwx 1 myname myname 11 8月  28 10:48 com29 -> /dev/ttyS28
lrwxrwxrwx 1 myname myname 10 8月  28 10:48 com3 -> /dev/ttyS2
lrwxrwxrwx 1 myname myname 11 8月  28 10:48 com30 -> /dev/ttyS29
lrwxrwxrwx 1 myname myname 11 8月  28 10:48 com31 -> /dev/ttyS30
lrwxrwxrwx 1 myname myname 11 8月  28 10:48 com32 -> /dev/ttyS31
lrwxrwxrwx 1 myname myname 10 8月  28 10:48 com4 -> /dev/ttyS3
lrwxrwxrwx 1 myname myname 10 8月  28 10:48 com5 -> /dev/ttyS4
lrwxrwxrwx 1 myname myname 10 8月  28 10:48 com6 -> /dev/ttyS5
lrwxrwxrwx 1 myname myname 10 8月  28 10:48 com7 -> /dev/ttyS6
lrwxrwxrwx 1 myname myname 10 8月  28 10:48 com8 -> /dev/ttyS7
lrwxrwxrwx 1 myname myname 10 8月  28 10:48 com9 -> /dev/ttyS8
lrwxrwxrwx 1 myname myname 17 8月  28 10:59 y: -> /home/myname
lrwxrwxrwx 1 myname myname  1 8月  28 10:59 z: -> /
CallApp Deepin-WeChat c:/Program Files/Tencent/WeChat/WeChat.exe
Disable auto update
rm: 无法删除'/home/myname/.deepinwine/Deepin-WeChat/drive_c/users/myname/Application Data/Tencent/WeChat/All Users/config/configEx.ini': 没有那个文件或目录
2019年 08月 28日 星期三 10:59:54 CST:kill WeChat.exe block
2019年 08月 28日 星期三 10:59:54 CST:tag bottle: 
Traceback (most recent call last):
  File "/opt/deepinwine/tools/get_tray_window", line 28, in <module>
    get_tray_window()
  File "/opt/deepinwine/tools/get_tray_window", line 18, in get_tray_window
    traymanager = bus.get_object("com.deepin.dde.TrayManager", "/com/deepin/dde/TrayManager")
  File "/usr/lib/python2.7/dist-packages/dbus/bus.py", line 241, in get_object
    follow_name_owner_changes=follow_name_owner_changes)
  File "/usr/lib/python2.7/dist-packages/dbus/proxies.py", line 248, in __init__
    self._named_service = conn.activate_name_owner(bus_name)
  File "/usr/lib/python2.7/dist-packages/dbus/bus.py", line 180, in activate_name_owner
    self.start_service_by_name(bus_name)
  File "/usr/lib/python2.7/dist-packages/dbus/bus.py", line 278, in start_service_by_name
    'su', (bus_name, flags)))
  File "/usr/lib/python2.7/dist-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.ServiceUnknown: The name com.deepin.dde.TrayManager was not provided by any .service files
2019年 08月 28日 星期三 10:59:54 CST:active bottles: 
/home/myname/.deepinwine/Deepin-WeChat/drive_c/Program Files/Tencent/WeChat
Starting process c:/Program Files/Tencent/WeChat/WeChat.exe ...
myname@myname:~/下载$ wine: cannot find L"C:\\windows\\system32\\winemenubuilder.exe"
wine version: 2.18

[0828/105955:INFO:exception_record.cc(518)] [QB]Process ID: 8 Type: 1
[0828/105956:ERROR:network_change_notifier_win.cc(156)] WSALookupServiceBegin failed with: 8

然后就一直没有任何响应,用top命令,可看到进程还在,并且占用较多的CPU

**Comment by zq1997** [comment]
同样症状，最新版微信不能运行的
