### ISSUE TITLE
多显示器，微信无法启动

### ISSUE THREAD

**Issue by XuCpeng** [wszqkzqk/deepin-wine-ubuntu#250]
Ubuntu : 18.04
deepinwine --version :  wine-2.18
WeChat : 2.6.8.65deepin0 (解决依赖问题版)

- 扩展双显示器的情况下，WeChat无法通过任何方式启动，CPU占用100%。
- 更换为单显示器可正常使用。
- 单显示器的情况下正常启动后，再切换为扩展双显示器，WeChat界面卡死，无法使用。

100%复现。

**Comment by cydia2020** [comment]
Same problem here
The issue disappears once I disable one of my monitors from system preferences.

`./run.sh 
Run Deepin-WeChat 2.6.8.65deepin0 c:/Program Files/Tencent/WeChat/WeChat.exe
run Deepin-WeChat progress pid 

lrwxrwxrwx 1 cydia2020 cydia2020 10 Mar 30 04:59 c: -> ../drive_c
lrwxrwxrwx 1 cydia2020 cydia2020 10 Mar 30 04:53 com1 -> /dev/ttyS0
lrwxrwxrwx 1 cydia2020 cydia2020 10 Mar 30 04:53 com10 -> /dev/ttyS9
lrwxrwxrwx 1 cydia2020 cydia2020 11 Mar 30 04:53 com11 -> /dev/ttyS10
lrwxrwxrwx 1 cydia2020 cydia2020 11 Mar 30 04:53 com12 -> /dev/ttyS11
lrwxrwxrwx 1 cydia2020 cydia2020 11 Mar 30 04:53 com13 -> /dev/ttyS12
lrwxrwxrwx 1 cydia2020 cydia2020 11 Mar 30 04:53 com14 -> /dev/ttyS13
lrwxrwxrwx 1 cydia2020 cydia2020 11 Mar 30 04:53 com15 -> /dev/ttyS14
lrwxrwxrwx 1 cydia2020 cydia2020 11 Mar 30 04:53 com16 -> /dev/ttyS15
lrwxrwxrwx 1 cydia2020 cydia2020 11 Mar 30 04:53 com17 -> /dev/ttyS16
lrwxrwxrwx 1 cydia2020 cydia2020 11 Mar 30 04:53 com18 -> /dev/ttyS17
lrwxrwxrwx 1 cydia2020 cydia2020 11 Mar 30 04:53 com19 -> /dev/ttyS18
lrwxrwxrwx 1 cydia2020 cydia2020 10 Mar 30 04:53 com2 -> /dev/ttyS1
lrwxrwxrwx 1 cydia2020 cydia2020 11 Mar 30 04:53 com20 -> /dev/ttyS19
lrwxrwxrwx 1 cydia2020 cydia2020 11 Mar 30 04:53 com21 -> /dev/ttyS20
lrwxrwxrwx 1 cydia2020 cydia2020 11 Mar 30 04:53 com22 -> /dev/ttyS21
lrwxrwxrwx 1 cydia2020 cydia2020 11 Mar 30 04:53 com23 -> /dev/ttyS22
lrwxrwxrwx 1 cydia2020 cydia2020 11 Mar 30 04:53 com24 -> /dev/ttyS23
lrwxrwxrwx 1 cydia2020 cydia2020 11 Mar 30 04:53 com25 -> /dev/ttyS24
lrwxrwxrwx 1 cydia2020 cydia2020 11 Mar 30 04:53 com26 -> /dev/ttyS25
lrwxrwxrwx 1 cydia2020 cydia2020 11 Mar 30 04:53 com27 -> /dev/ttyS26
lrwxrwxrwx 1 cydia2020 cydia2020 11 Mar 30 04:53 com28 -> /dev/ttyS27
lrwxrwxrwx 1 cydia2020 cydia2020 11 Mar 30 04:53 com29 -> /dev/ttyS28
lrwxrwxrwx 1 cydia2020 cydia2020 10 Mar 30 04:53 com3 -> /dev/ttyS2
lrwxrwxrwx 1 cydia2020 cydia2020 11 Mar 30 04:53 com30 -> /dev/ttyS29
lrwxrwxrwx 1 cydia2020 cydia2020 11 Mar 30 04:53 com31 -> /dev/ttyS30
lrwxrwxrwx 1 cydia2020 cydia2020 11 Mar 30 04:53 com32 -> /dev/ttyS31
lrwxrwxrwx 1 cydia2020 cydia2020 10 Mar 30 04:53 com4 -> /dev/ttyS3
lrwxrwxrwx 1 cydia2020 cydia2020 10 Mar 30 04:53 com5 -> /dev/ttyS4
lrwxrwxrwx 1 cydia2020 cydia2020 10 Mar 30 04:53 com6 -> /dev/ttyS5
lrwxrwxrwx 1 cydia2020 cydia2020 10 Mar 30 04:53 com7 -> /dev/ttyS6
lrwxrwxrwx 1 cydia2020 cydia2020 10 Mar 30 04:53 com8 -> /dev/ttyS7
lrwxrwxrwx 1 cydia2020 cydia2020 10 Mar 30 04:53 com9 -> /dev/ttyS8
lrwxrwxrwx 1 cydia2020 cydia2020  8 Mar 30 04:07 d:: -> /dev/sdb
lrwxrwxrwx 1 cydia2020 cydia2020 17 Mar 30 04:07 e: -> /media/wayne/Ntfs
lrwxrwxrwx 1 cydia2020 cydia2020  9 Mar 30 04:07 e:: -> /dev/sdb1
lrwxrwxrwx 1 cydia2020 cydia2020  8 Mar 30 04:07 f:: -> /dev/sr0
lrwxrwxrwx 1 cydia2020 cydia2020 15 Mar 30 04:59 y: -> /home/cydia2020
lrwxrwxrwx 1 cydia2020 cydia2020  1 Mar 30 04:59 z: -> /
CallApp Deepin-WeChat c:/Program Files/Tencent/WeChat/WeChat.exe
Disable auto update
rm: '/home/cydia2020/.deepinwine/Deepin-WeChat/drive_c/users/cydia2020/Application Data/Tencent/WeChat/All Users/config/configEx.ini' を削除できません: そのようなファイルやディレクトリはありません
Mon 30 Mar 04:59:51 AEDT 2020:kill WeChat.exe block
Mon 30 Mar 04:59:51 AEDT 2020:tag bottle: /home/cydia2020/.deepinwine/Deepin-WeChat
Traceback (most recent call last):
  File "/opt/deepinwine/tools/get_tray_window", line 28, in <module>
    get_tray_window()
  File "/opt/deepinwine/tools/get_tray_window", line 18, in get_tray_window
    traymanager = bus.get_object("com.deepin.dde.TrayManager", "/com/deepin/dde/TrayManager")
  File "/usr/lib/python2.7/dist-packages/dbus/bus.py", line 243, in get_object
    follow_name_owner_changes=follow_name_owner_changes)
  File "/usr/lib/python2.7/dist-packages/dbus/proxies.py", line 250, in __init__
    self._named_service = conn.activate_name_owner(bus_name)
  File "/usr/lib/python2.7/dist-packages/dbus/bus.py", line 182, in activate_name_owner
    self.start_service_by_name(bus_name)
  File "/usr/lib/python2.7/dist-packages/dbus/bus.py", line 280, in start_service_by_name
    'su', (bus_name, flags)))
  File "/usr/lib/python2.7/dist-packages/dbus/connection.py", line 653, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.ServiceUnknown: The name com.deepin.dde.TrayManager was not provided by any .service files
Mon 30 Mar 04:59:51 AEDT 2020:active bottles: 
Mon 30 Mar 04:59:51 AEDT 2020:try to kill /home/cydia2020/.deepinwine/Deepin-WeChat
Mon 30 Mar 04:59:51 AEDT 2020:kill /home/cydia2020/.deepinwine/Deepin-WeChat deepinwine
/home/cydia2020/.deepinwine/Deepin-WeChat/drive_c/Program Files/Tencent/WeChat
Starting process c:/Program Files/Tencent/WeChat/WeChat.exe ...
/opt/deepinwine/apps/Deepin-WeChat$ wine: cannot find L"C:\\windows\\system32\\winemenubuilder.exe"
wine version: 2.18

[0330/045952:INFO:exception_record.cc(518)] [QB]Process ID: 8 Type: 1
[0330/045952:ERROR:network_change_notifier_win.cc(156)] WSALookupServiceBegin failed with: 8
`

**Comment by huangsiyuan924** [comment]
我也遇到了这个问题， 单核cpu直接100%

**Comment by huangdaren1997** [comment]
先单屏启动，登录以后再开启多屏０．０

**Comment by duanfa** [comment]
我也遇到了，希望码主更新一版

**Comment by lijie-jiang** [comment]
同样的问题，很头疼，请问有人解决了吗？

**Comment by tangruize** [comment]
降级到[2.6.2.31](https://mirrors.aliyun.com/deepin/pool/non-free/d/deepin.com.wechat/deepin.com.wechat_2.6.2.31deepin0_i386.deb)就可以了. ([来源](https://bbs.deepin.org/forum.php?mod=viewthread&tid=182179&page=1#pid616278))
仓库里保留了这个旧版本, 说明他们注意到过这个问题.

**Comment by jakepu** [comment]
> 降级到[2.6.2.31](https://mirrors.aliyun.com/deepin/pool/non-free/d/deepin.com.wechat/deepin.com.wechat_2.6.2.31deepin0_i386.deb)就可以了. ([来源](https://bbs.deepin.org/forum.php?mod=viewthread&tid=182179&page=1#pid616278))
> 仓库里保留了这个旧版本, 说明他们注意到过这个问题.

我试了还是不行

**Comment by Limaomao821** [comment]
https://gitee.com/wszqkzqk/deepin-wine-containers-for-ubuntu
用这个仓库中的2.6.2.31版本的微信，不要用2.6.8.65版本

**Comment by GalSang17** [comment]
换到这个低版本的还是不行

**Comment by abcfyk** [comment]
> 换到这个低版本的还是不行

单屏启动，登录完成后，再启用双屏。注意不要把微信拖到2号显示器上去，保留在主显示器上可以正常使用

**Comment by tangruize** [comment]
用这个吧，electronic-wechat
https://github.com/kooritea/electronic-wechat/releases/tag/v2.3.1

**Comment by duanfa** [comment]
ubuntu20.04   wechat2.9.5.41 ，可以启动，托盘没有通知的，然后主副屏幕互换一下，所有问题解决

**Comment by yangrisheng** [comment]
> ubuntu20.04 wechat2.9.5.41 ，可以启动，托盘没有通知的，然后主副屏幕互换一下，所有问题解决

哪里有安装教程吗

**Comment by yanliang-wang** [comment]
> 先单屏启动，登录以后再开启多屏０．０

这种方法虽然比较dirty，但是也还算好使，下面是命令行的启动方式

```bash
# 首先通过xrandr查看自己两个显示器的编号，我这里副显示器是DP-5，主显示器是HDMI-0
xrandr --output DP-5 --off && sh /opt/deepinwine/apps/Deepin-WeChat/run.sh && sleep 3 &&  xrandr --output DP-5 --right-of HDMI-0 --auto
```
