### ISSUE TITLE
mint19 TIM 启动时闪退，wechat 消息自动弹出

### ISSUE THREAD

**Issue by bash-c** [wszqkzqk/deepin-wine-ubuntu#50]
感谢作者的贡献，我在使用过程中遇到 TIM 打开闪退，wechat 收到新消息自动弹出等问题。

----
系统信息
```bash
~ lsb_release -a
No LSB modules are available.
Distributor ID:	LinuxMint
Description:	Linux Mint 19 Tara
Release:	19
Codename:	tara
```

遇到 TIM 在登录时闪退的问题，shell 里启动发现如下报错：
```bash
~ "/opt/deepinwine/apps/Deepin-TIM/run.sh" -u %u 
realpath: 缺少操作数
Try 'realpath --help' for more information.
2018年 12月 03日 星期一 14:51:47 CST:Run Deepin-TIM 2.0.0deepin4
2018年 12月 03日 星期一 14:51:47 CST:run Deepin-TIM progress pid 
Gtk-Message: 14:51:47.330: GtkDialog mapped without a transient parent. This is discouraged.
总用量 0
lrwxrwxrwx 1 m4x m4x 10 12月  3 14:51 c: -> ../drive_c
lrwxrwxrwx 1 m4x m4x 10 12月  3 14:51 com1 -> /dev/ttyS0
lrwxrwxrwx 1 m4x m4x 10 12月  3 14:51 com10 -> /dev/ttyS9
lrwxrwxrwx 1 m4x m4x 11 12月  3 14:51 com11 -> /dev/ttyS10
lrwxrwxrwx 1 m4x m4x 11 12月  3 14:51 com12 -> /dev/ttyS11
lrwxrwxrwx 1 m4x m4x 11 12月  3 14:51 com13 -> /dev/ttyS12
lrwxrwxrwx 1 m4x m4x 11 12月  3 14:51 com14 -> /dev/ttyS13
lrwxrwxrwx 1 m4x m4x 11 12月  3 14:51 com15 -> /dev/ttyS14
lrwxrwxrwx 1 m4x m4x 11 12月  3 14:51 com16 -> /dev/ttyS15
lrwxrwxrwx 1 m4x m4x 11 12月  3 14:51 com17 -> /dev/ttyS16
lrwxrwxrwx 1 m4x m4x 11 12月  3 14:51 com18 -> /dev/ttyS17
lrwxrwxrwx 1 m4x m4x 11 12月  3 14:51 com19 -> /dev/ttyS18
lrwxrwxrwx 1 m4x m4x 10 12月  3 14:51 com2 -> /dev/ttyS1
lrwxrwxrwx 1 m4x m4x 11 12月  3 14:51 com20 -> /dev/ttyS19
lrwxrwxrwx 1 m4x m4x 11 12月  3 14:51 com21 -> /dev/ttyS20
lrwxrwxrwx 1 m4x m4x 11 12月  3 14:51 com22 -> /dev/ttyS21
lrwxrwxrwx 1 m4x m4x 11 12月  3 14:51 com23 -> /dev/ttyS22
lrwxrwxrwx 1 m4x m4x 11 12月  3 14:51 com24 -> /dev/ttyS23
lrwxrwxrwx 1 m4x m4x 11 12月  3 14:51 com25 -> /dev/ttyS24
lrwxrwxrwx 1 m4x m4x 11 12月  3 14:51 com26 -> /dev/ttyS25
lrwxrwxrwx 1 m4x m4x 11 12月  3 14:51 com27 -> /dev/ttyS26
lrwxrwxrwx 1 m4x m4x 11 12月  3 14:51 com28 -> /dev/ttyS27
lrwxrwxrwx 1 m4x m4x 11 12月  3 14:51 com29 -> /dev/ttyS28
lrwxrwxrwx 1 m4x m4x 10 12月  3 14:51 com3 -> /dev/ttyS2
lrwxrwxrwx 1 m4x m4x 11 12月  3 14:51 com30 -> /dev/ttyS29
lrwxrwxrwx 1 m4x m4x 11 12月  3 14:51 com31 -> /dev/ttyS30
lrwxrwxrwx 1 m4x m4x 11 12月  3 14:51 com32 -> /dev/ttyS31
lrwxrwxrwx 1 m4x m4x 10 12月  3 14:51 com4 -> /dev/ttyS3
lrwxrwxrwx 1 m4x m4x 10 12月  3 14:51 com5 -> /dev/ttyS4
lrwxrwxrwx 1 m4x m4x 10 12月  3 14:51 com6 -> /dev/ttyS5
lrwxrwxrwx 1 m4x m4x 10 12月  3 14:51 com7 -> /dev/ttyS6
lrwxrwxrwx 1 m4x m4x 10 12月  3 14:51 com8 -> /dev/ttyS7
lrwxrwxrwx 1 m4x m4x 10 12月  3 14:51 com9 -> /dev/ttyS8
lrwxrwxrwx 1 m4x m4x  8 12月  3 11:46 d:: -> /dev/sda
lrwxrwxrwx 1 m4x m4x  1 12月  3 14:51 z: -> /
2018年 12月 03日 星期一 14:51:47 CST:CallApp Deepin-TIM %u 
2018年 12月 03日 星期一 14:51:47 CST:kill TIM.exe block
2018年 12月 03日 星期一 14:51:47 CST:tag bottle: 
Traceback (most recent call last):
  File "/opt/deepinwine/tools/get_tray_window", line 28, in <module>
    get_tray_window()
  File "/opt/deepinwine/tools/get_tray_window", line 18, in get_tray_window
    traymanager = bus.get_object("com.deepin.dde.TrayManager", "/com/deepin/dde/TrayManager")
  File "/usr/lib/python2.7/dist-packages/dbus/bus.py", line 241, in get_object
    follow_name_owner_changes=follow_name_owner_changes)
  File "/usr/lib/python2.7/dist-packages/dbus/proxies.py", line 248, in __init__
    self._named_service = conn.activate_name_owner(bus_name)
  File "/usr/lib/python2.7/dist-packages/dbus/bus.py", line 180, in activate_name_owner
    self.start_service_by_name(bus_name)
  File "/usr/lib/python2.7/dist-packages/dbus/bus.py", line 278, in start_service_by_name
    'su', (bus_name, flags)))
  File "/usr/lib/python2.7/dist-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.ServiceUnknown: The name com.deepin.dde.TrayManager was not provided by any .service files
2018年 12月 03日 星期一 14:51:47 CST:active bottles: 
2018年 12月 03日 星期一 14:51:47 CST:start running...
~ X Error of failed request:  BadMatch (invalid parameter attributes)
  Major opcode of failed request:  139 (RENDER)
  Minor opcode of failed request:  4 (RenderCreatePicture)
  Serial number of failed request:  264
  Current serial number in output stream:  297
wine: cannot find L"c:\\Program Files\\Tencent\\TIM\\Bin\\TXPlatform.exe"
init server success 127.0.0.1 12291
```
缺少 `TXPlatform.exe`。我是用 deb 安装的 TIM。

同时遇到 wechat 收到新消息自动弹出的问题。

**Comment by bash-c** [comment]
还遇到了 mint19 wechat 不能使用摄像头的问题

**Comment by Peytonlan** [comment]
Mint 19 Cinnamon 已测, TIM启动及视频通话都正常
微信未测试, qq微信其实我都不用, qq借朋友的小号做的测试, 微信没好意思借, 但估计问题不大

测试环境:
Cinnamon2d@Xspice@19@Mint@LXD@Snappy@28@Fedora@LXD@Snappy@28@Fedora

参照:
https://github.com/wszqkzqk/deepin-wine-ubuntu/issues/12

**Comment by bash-c** [comment]
@Peytonlan 我的屏幕显示 TIM 不正常，按照网上的方法
```bash
WINEPREFIX=~/.deepinwine/Deepin-TIM deepin-wine winecfg
```
设置了一下 deepin-wine 的缩放，之后就打不开了，会不会是因为这个原因。

**Comment by Peytonlan** [comment]
删除掉 ~/.deepinwine/Deepin-TIM
重新执行 /opt/deepinwine/apps/Deepin-TIM/run.sh

**Comment by bash-c** [comment]
> 删除掉 ~/.deepinwine/Deepin-TIM
> 重新执行 /opt/deepinwine/apps/Deepin-TIM/run.sh

这样操作后确实可以登录了。
但使用 `WINEPREFIX=~/.deepinwine/Deepin-TIM deepin-wine winecfg` 设置分辨率后再次 crash。经过尝试发现设置屏幕分辨率大于某个值后就会发生不能登录的情况，wechat上也遇到了相同的问题。

另外还有个问题是wechat和TIM接受到新消息都会自动弹出窗口。

**Comment by Peytonlan** [comment]
你所说的设置分辨率是指按照 https://github.com/wszqkzqk/deepin-wine-ubuntu/issues/45 这个设置, 改了dpi么
我试过改到200也没出现你所说的崩溃现象, qq收到新消息也未自动弹出窗口
如果不是请给出具体的数值, 我试下

可尝试创建一个新的用户, 以新用户运行
如果新用户未出现此现象, 说明当前用户的某个设置, 影响了运行
如果新用户现象依旧, 怀疑系统安装不正常
可新开一虚拟机, 重复你的安装步骤, 看虚拟机内是否运行正常

**Comment by bash-c** [comment]
对，改了dpi。
经过尝试dpi ≥ 205时 TIM 不能启动。
新账户和虚拟机也出现了相同的情况。

**Comment by Peytonlan** [comment]
已确认, 在 Deepin 15.8 上也有这个问题, 不是 Mint 19 的系统问题
标准版的 Wine 3.0 & 3.6 没有这个问题, 等 deepin 的后继升级吧
另外, 收到新消息会自动弹出窗口, QQ的设置中有没有关闭相关选项

**Comment by bash-c** [comment]
已关闭 “允许来消息时自动弹出窗口”，wechat 也关闭了相关选项。
后来仔细看了一下不能使用摄像头是因为没找到摄像头
![](http://ww1.sinaimg.cn/large/006AWYXBly1fy0hag8dj5j30iz0d6gm7.jpg)
或者说不能使用摄像头（点击打开预览画面）TIM 退出，不确定是哪种情况。
不过估计也是跟 deepin-wine 的版本有关了。。。

**Comment by Peytonlan** [comment]
摄像头的解决方法已在 https://github.com/wszqkzqk/deepin-wine-ubuntu/issues/12#issuecomment-444172543 提到, 可能你没仔细看

**Comment by bash-c** [comment]
摄像头的问题解决了。
后来发现关闭 TIM 或者 wechat 的窗口（点右上角的 x），下次新消息就不会自动弹出。但带来的一个问题是快速打开窗口的快捷键（ctrl + alt + Z, ctrl + clt + W）失效

**Comment by duaneya** [comment]
输入法好使吗 mint 微信 ，我也是一有新消息就弹到最上面了，搜狗输入不了

**Comment by Deali-Axy** [comment]
来看一下，自动弹出窗口的问题依然存在。

**Comment by yklove** [comment]
来看一下，自动弹出窗口的问题依然存在。

**Comment by chenshanhai-mc** [comment]
来看一下，自动弹出窗口的问题依然存在
mint 20.1， 4k屏，  QQdpi超过180就获取不了光标，无法输入与确认登录
窗口没x掉的情况，有消息会自动弹出，比如在写文档的时候，突然就会弹出qq，然后输入到qq里面去了。
